services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: postgres   
      POSTGRES_DB: tron_scan_lite         
    ports:
      - "5432:5432"                 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - work

  tron_service:
    build:
      context: .
    container_name: tron_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - work

networks:
  work:
    driver: bridge
    
volumes:
  postgres_data: